### BTest baseline data generated by btest-diff. Do not edit. Use "btest -U/-u" to update. Requires BTest >= 0.63.
  version = "1.0.0.dev2",  # with comment
  version = "1.0.0.dev2",  # another comment
  version = "1.0.0.dev2",  # Python style
  version = "0.0.1.nope"   # should not change
...
