ci_template: &CI_TEMPLATE
  only_if: >
    $CIRRUS_PR != '' ||
    ( $CIRRUS_REPO_NAME == 'zeek-archiver' &&
      (
      $CIRRUS_BRANCH == 'master' ||
      $CIRRUS_BRANCH =~ 'release/.*'
      )
    )

  build_script: ./ci/build.sh
  test_script: ./test.sh

# Linux EOL timelines: https://linuxlifecycle.com/
# Fedora (~13 months): https://fedoraproject.org/wiki/Fedora_Release_Life_Cycle

fedora33_task:
  container:
    # Fedora 33 EOL: Around November 2022
    dockerfile: ci/fedora-33/Dockerfile
  << : *CI_TEMPLATE

fedora32_task:
  container:
    # Fedora 32 EOL: Around May 2021
    dockerfile: ci/fedora-32/Dockerfile
  << : *CI_TEMPLATE

centos7_task:
  container:
    # CentOS 7 EOL: June 30, 2024
    dockerfile: ci/centos-7/Dockerfile
  << : *CI_TEMPLATE

centos8_task:
  container:
    # CentOS 8 EOL: May 31, 2029
    dockerfile: ci/centos-8/Dockerfile
  << : *CI_TEMPLATE

debian10_task:
  container:
    # Debian 10 EOL: June 2024
    dockerfile: ci/debian-10/Dockerfile
  << : *CI_TEMPLATE

debian9_task:
  container:
    # Debian 9 EOL: June 2022
    dockerfile: ci/debian-9/Dockerfile
  << : *CI_TEMPLATE

debian9_32bit_task:
  container:
    # Debian 9 EOL: June 2022
    dockerfile: ci/debian-9-32bit/Dockerfile
  << : *CI_TEMPLATE

ubuntu20_task:
  container:
    # Ubuntu 20.04 EOL: April 2025
    dockerfile: ci/ubuntu-20.04/Dockerfile
  << : *CI_TEMPLATE

ubuntu18_task:
  container:
    # Ubuntu 18.04 EOL: April 2023
    dockerfile: ci/ubuntu-18.04/Dockerfile
  << : *CI_TEMPLATE

ubuntu16_task:
  container:
    # Ubuntu 16.04 EOL: April 2021
    dockerfile: ci/ubuntu-16.04/Dockerfile
  << : *CI_TEMPLATE

# Apple doesn't publish official long-term support timelines.
# We aim to support both the current and previous macOS release.
macos_big_sur_task:
  osx_instance:
    image: big-sur-base
  prepare_script: ./ci/macos/prepare.sh
  << : *CI_TEMPLATE

macos_catalina_task:
  osx_instance:
    image: catalina-base
  prepare_script: ./ci/macos/prepare.sh
  << : *CI_TEMPLATE

# FreeBSD EOL timelines: https://www.freebsd.org/security/security.html#sup
freebsd12_task:
  freebsd_instance:
    # FreeBSD 12 EOL: June 30, 2024
    image_family: freebsd-12-2
  prepare_script: ./ci/freebsd/prepare.sh
  << : *CI_TEMPLATE

freebsd11_task:
  freebsd_instance:
    # FreeBSD 11 EOL: September 30, 2021
    image_family: freebsd-11-4
  prepare_script: ./ci/freebsd/prepare.sh
  << : *CI_TEMPLATE
